config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Routes are matched top to bottom.

  match '/auth/:provider/callback', to: 'authentications#create', via: :all
  get '/auth/failure', to: 'home#auth_failure'
  devise_for :users, controllers: {
    registrations: 'registrations',
    confirmations: 'confirmations',
    sessions: 'sessions',
    passwords: 'passwords'
  }
  devise_scope :user do
    get   '/profile', to: 'registrations#profile', as: :user_profile
    match '/profile', to: 'registrations#profile', as: :update_user_profile, via: [:put,:patch]
    match '/change_password', to: 'registrations#change_password', as: :change_password, via: [:get,:put,:patch]
    match '/users/sign_out', to: 'sessions#destroy', as: :delete_user_session, via: [:get,:post,:put,:patch,:delete]
    get   '/register', to: 'registrations#new', as: :register
    get   '/login',    to: 'sessions#new',      as: :login
    match '/logout',   to: 'sessions#destroy',  as: :logout, via: [:get,:post,:put,:patch,:delete]
  end
  resources :authentications
  get '/invitation/:token', to: 'invitations#accept', as: :invitation

  get '/dashboard', to: 'dashboard#index', as: :dashboard

  get '/privacy', to: 'home#privacy', as: :privacy
  get '/terms',   to: 'home#terms',   as: :terms
  get '/about',   to: 'home#about',   as: :about
  get '/contact', to: 'home#contact', as: :contact
  get '/help',    to: 'home#help',    as: :help

  require 'subdomain'
  constraints(Subdomain) do
    # Change this action to serve subdomain-specific content as the root page,
    get '/', to: 'home#subdomain_specific_index'
  end

  ActiveAdmin.routes(self)

  root to: 'home#index'

  mount Sidekiq::Web, at: Rails.configuration.sidekiq.web.mount_point

  # Status check URL
  get 'ping' => proc {|env| [200, {}, ['pong']] }

  # Must be last in line
  # Catch unroutable paths and send to the routing error handler
  match '*a', to: 'home#routing_error', via: :all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include UrlHelper

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :make_action_mailer_use_request_host

  # Entire app requires authentication
  # Require all controllers to authorize the user for the current action.
  # If a controller doesn't, you'll get an exception.
  check_authorization unless: :skip_authorization?
  before_action :require_login
  after_action :store_location

  ##
  # If an Access Denies exception is raised, do this instead of showing the results of an uncaught exception.
  rescue_from CanCan::AccessDenied, with: :render_access_denied
  rescue_from SecurityError, with: :render_access_denied

  def routing_error
    fail ActionController::RoutingError.new 'Page not found'
  end

  protected

  def ensure_json_request
    return if json_request?
    render_access_denied
  end

  def json_request?
    !!(
      request.xhr? ||
      request.headers["Accept"] =~ /json/ ||
      params[:format] == "json" ||
      request.format == Mime::JSON
    )
  end

  def content_nav(template = nil)
    @content_nav_template = template || 'content_nav'
  end

  def make_action_mailer_use_request_host
    ActionMailer::Base.default_url_options[:host] = request.host_with_port
  end

  def user_timezone
    cookies['time_zone'] || 'US/Eastern'
  end

  def set_timezone
    Time.zone = user_timezone
  end

  def flash_message(type, message)
    flash[type] = message
  end

  ########
  # Authentication and Authorization
  #
  def self.skip_authentication(*args)
    skip_before_action :require_login, *args
    skip_before_action :require_no_authentication, *args
  end

  def require_login
    unless logged_in?
      if json_request?
        render_error(:access_denied)
      else
        store_location
        redirect_to login_path
      end
    end
  end

  def logged_in?
    !!current_user
  end

  ##
  # Checks for a user being logged in and makes sure they're an admin.
  def authenticate_admin!
    authenticate_user!
    fail SecurityError unless current_user.admin?
  end

  def skip_authorization?
    # Within our own controllers, it's important that authorization
    # be left enabled so that we never forget to either call
    # authorize_resource or authorize! within each action. The
    # ActiveAdmin authorization adapter does not call authorize!, even
    # though it does use CanCan to check authorization and filter
    # records. So we must not require it to.
    # We also want to skip this for Devise.
    kind_of?(ActiveAdmin::BaseController) || respond_to?(:devise_controller?)
  end

  ########
  # Redirection
  #

  # REF: https://github.com/plataformatec/devise/wiki/How-To:-Redirect-back-to-current-page-after-sign-in,-sign-out,-sign-up,-update
  # Store location for redirection
  def store_location
    # store last url as long as it is an HTTP GET and isn't a login or logout path
    session[:return_to_path] = request.fullpath if storable_request?
  end

  def storable_request?
    # only GETs and not ignored paths
    !!(request.get? && !ignored_paths.include?(request.path))
  end

  def return_to_path
    session[:return_to_path] if valid_return_to_path?
  end

  def valid_return_to_path?
    !!(
      session.key?(:return_to_path) &&
      !session[:return_to_path].blank? &&
      ignored_paths.include?(
        URI.parse(session[:return_to_path]).path
      )
    )
  end

  def ignored_paths
    [
      root_path,
      user_registration_path,
      new_user_registration_path,
      cancel_user_registration_path,
      register_path,
      user_session_path,
      new_user_session_path,
      login_path,
      destroy_user_session_path,
      logout_path,
      user_password_path,
      new_user_password_path,
      user_confirmation_path,
      new_user_confirmation_path,
      user_unlock_path,
      new_user_unlock_path
    ]
  end

  def user_path(user)
    user.admin? ? admin_dashboard_path : dashboard_path
  end

  def after_sign_up_path_for(user)
    return_to_path || signed_in_root_path(resource)
  end

  def after_sign_in_path_for(user)
    return_to_path || signed_in_root_path(resource)
  end

  def signed_in_root_path(user)
    return_to_path || user_path(user)
  end

  def after_sign_out_path_for(user)
    login_path
  end

  def after_update_path_for(user)
    logged_in? ? (return_to_path || profile_path) : root_path
  end

  def auth_failure(user)
    redirect_to(return_to_path || root_path)
  end

  #######
  # Error handling
  #

  unless Rails.application.config.consider_all_requests_local
    rescue_from(
      Exception,
      with: ->(exception) { render_error :internal_server_error, 500, exception }
    )
    rescue_from(
      ActionController::RoutingError,
      ActionController::UnknownController,
      ::AbstractController::ActionNotFound,
      ActiveRecord::RecordNotFound,
      with: ->(exception) { render_error :not_found, 404, exception }
    )
    rescue_from(
      SecurityError,
      CanCan::AccessDenied,
      with: ->(exception) { render_error :access_denied, 403, exception }
    )
  end

  def render_access_denied
    render_error :access_denied, 403
  end

  def render_not_found
    render_error :not_found, 404
  end

  def render_error(type, code = 500,  exception = nil)
    # Send exception to Sentry
    capture_exception(exception) if exception
    Rails.logger.error(
      "Rendering error '#{type.to_s}' because of #{exception.class}: "\
      "#{exception.message}"
    ) if exception
    respond_to do |format|
      format.html { render status: code, template: "errors/#{type.to_s}", layout: 'error' }
      format.json { render status: code, text: { error: type.to_s.titleize }.to_json, content_type: Mime::JSON }
      format.text { render status: code, text: type.to_s.titleize }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  SidebarPanel = Struct.new(:type, :heading, :messages, :name) do
    # self.name = heading.underscore if heading.present? && name.blank?
    def add_message(message)
      self.messages ||= []
      self.messages << message
    end
  end

  def create_sidebar_panel(hash)
    sidebar_panels << SidebarPanel.new(hash[:type], hash[:heading], hash[:messages], hash[:name])
    sidebar_panels.last
  end

  def sidebar_panels
    @sidebar_panels ||= []
  end

  def display_base_errors(resource)
    return '' if (resource.errors.empty?) || (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

  ##
  # Extend Flash to allow for additional message types
  def bootstrap_class_for_flash(flash_type)
    case flash_type.to_sym
      when :error, :alert
        'alert-danger'
      when :notice
        'alert-info'
      when :warn
        'alert-warning'
      else
        "alert-#{flash_type.to_s}"
    end
  end

  # FIXME: this preferred_time_zone should be a class method that uses a config default
  def current_timezone
    if current_user.present?
      tz = current_user.preferred_time_zone
    else
      tz = User.new.preferred_time_zone
    end
    ActiveSupport::TimeZone.new tz.gsub(' ', '_')
  end

  def devise_resource_name
    :user
  end

  def devise_resource
    @devise_resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def social_networks
    SocialNetwork.enabled.sort { |a, b| a.short_name <=> b.short_name }
  end

  def current_or_guest_user
    if user_signed_in?
      if session[:guest_user_id]

        # Hand over data if guest logs in
        #
        # data goes here
        #
        current_user.save!

        guest_user.destroy
        session[:guest_user_id] = nil
      end
      current_user
    else
      guest_user
    end
  end

  private

  def guest_user
    @cached_guest_user ||= User.find(session[:guest_user_id] ||= create_guest_user.id)
  rescue ActiveRecord::RecordNotFound # if session[:guest_user_id] invalid
    session[:guest_user_id] = nil
    guest_user
  end

  def create_guest_user
    # http://stackoverflow.com/questions/7465467/devise-create-user-account-with-confirmed-without-sending-out-an-email
    u = User.new name: 'guest', email: "guest_user_#{Time.zone.now.to_i}#{rand(99)}"
    u.skip_confirmation!
    u.save! validate: false
    session[:guest_user_id] = u.id
    u
  end
end

app/views/application/_footer.slim
#footer
  .navbar.navbar-inverse role="navigation"
    .container-fluid
      #copyright &copy;#{copyright_year} #{copyright_author} 
      .navbar-header
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-footer_links"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
      .navbar-collapse.navbar-footer_links.collapse
        = tabs_tag namespace: :footer_links, open_tabs: {id: 'footer-links', class: 'nav navbar-nav inline'} do |tab|
          = tab.privacy 'About', privacy_path
          = tab.terms   'Terms', terms_path
          = tab.help    'Help',  help_path
  - if content_for?(:footer)
    .well
      = yield(:footer) 

app/views/application/_google_analytics.slim
- if Rails.configuration.google_analytics.ua && Rails.configuration.google_analytics.domain
  /! Google Analytics (Universal)
  javascript:
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', '#{Rails.configuration.google_analytics.ua}', '#{Rails.configuration.google_analytics.domain}');
    ga('send', 'pageview');
  /! End Google Analytics (Universal)

app/views/application/_header.slim
#header.navbar.navbar-inverse role="navigation"
  .container-fluid
    .navbar-header
      = link_to root_path, {class: "brand"} do |l|
        = image_tag 'olpc_math_logo.svg', {class: "logo navbar-brand"}
      button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-main_nav"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar

    .navbar-collapse.navbar-main_nav.collapse
      = tabs_tag namespace: :main_nav, open_tabs: {id: 'main-nav', class: 'nav navbar-nav'} do |tab|
        = tab.about 'About', about_path
        = tab.contact   'Contact', contact_path
        li.dropdown = link_to "#", {class: "dropdown-toggle", data: {toggle: "dropdown"}} do
          span Dropdown
          b.caret
          ul class="dropdown-menu"
            li = link_to "Action", "#"
            li = link_to "Another action", "#"
            li = link_to "Something else here", "#"
            li.divider
            li.dropdown-header Nav header
            li = link_to "Separated link", "#"
            li = link_to "One more separated link", "#"
      = render "user_nav"

app/views/application/_messages.slim
#flashes data-flash-messages="#{flash.to_json}"
  - flash.each do |name, msg|
    .alert.fade.in class="#{name} #{bootstrap_class_for_flash(name)}"
      a.close data-dismiss="alert" &#215;
      = content_tag :div, msg, :id => "flash_#{name}"
  - flash.clear

// Convert flash messages to use Handlebars templates and get rendered
// using JavaScript, this allows the display of the same flashes by AJAX calls
/ <script id="flash-template" type="text/x-handlebars-template">
/   .alert.fade.in class="{{name}} {{class_name}}"
/     a.close data-dismiss="alert" &#215;
/       div id="flash_{{name}}"
/         | {{message}}
/     br.clear
/ </script>
/ javascript:
/   flash_template = Handlebars.compile(jQuery("#flash-template").html());
/   function show_flash(name,message) {
/     jQuery('#flashes').html(flash_template({name: name, class_name: #{bootstrap_class_for_flash(name)}, message: message}));
/   }

app/views/application/_sentry.slim
- if Rails.configuration.sentry.present? && Rails.configuration.sentry.javascript_enabled
  script src="//d3nslu0hdya83q.cloudfront.net/dist/1.0/raven.min.js"
  javascript:
    try {
      opts = {};
      Raven.config('#{Rails.configuration.sentry.javascript_dsn}', opts).install();
    } catch(e) {}

app/views/application/_shared_head.slim
title == (content_for?(:title) ? (yield(:title) << ' : ') : '' ) << Rails.application.name
- Rails.logger.warn('No page title set') unless content_for?(:title)

meta charset="utf-8"
meta name='viewport' content='width=device-width, initial-scale=1.0'

link rel='icon' type='images/svg' href="#{asset_path('olpc_math_logo.svg')}"
link rel='apple-touch-icon' type='images/svg' href="#{asset_path('olpc_math_logo.svg')}"

/ Open Sans
= stylesheet_link_tag '//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800'
/ Bootstrap
= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css'

/ FontAwesome
= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css'

= stylesheet_link_tag :application

= render 'sentry'
= render 'google_analytics'

= include_gon
javascript:
  window.MATH_APP = window.gon || {};

= javascript_include_tag '//ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js'
= javascript_include_tag '//ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-route.js'
= javascript_include_tag '//ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-resource.js'
= javascript_include_tag '//code.jquery.com/jquery-2.1.3.min.js'
= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js'
= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.13.0/ui-bootstrap-tpls.min.js'

= javascript_include_tag :application

= csrf_meta_tags

== yield(:head)

app/views/application/_user_nav.slim
= tabs_tag namespace: :user_nav, open_tabs: {id: 'user-nav', class: 'nav navbar-nav navbar-right'} do |tab|
  - if user_signed_in?
    li = link_to "#", {class: "dropdown-toggle", data: {toggle: "dropdown"}} do
      span = image_tag current_user.avatar_url, {class: 'navbar-avatar'}
      span #{current_user.display_name}
      b.caret
      ul class="dropdown-menu"
        li = link_to "Edit profile", user_profile_path
        li = link_to "Administration", admin_dashboard_path if current_user.has_role?(:admin)
        li = link_to "Log Out", logout_path, method: :delete
  - else
    = tab.register 'Register', register_path
    = tab.login 'Log In', login_path

app/views/application/_userreport.slim
if Rails.configuration.userreport.site_id.present?
  javascript:
    var _urq = _urq || []; _urq.push(['initSite', '#{Rails.configuration.userreport.site_id}']);
    (function() {var ur=document.createElement('script');ur.type='text/javascript';ur.async=true;ur.src='https://cdn.userreport.com/userreport.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(ur,s);})();